version: '3'
services:
  devops:
    privileged: true 
    image: devops:1.3
    build: .
    restart: always
    container_name: devops
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
      -  /usr/bin/docker:/usr/bin/docker
    ports:
      - "8090:80"
